datasets:
  time_step: 4000 #milliseconds
  data_dir: "/Users/anhnd/CodingSpace/Python/W"
  tmp_dir : "/Users/anhnd/CodingSpace/Python/W"
  out_dir: "/Users/anhnd/CodingSpace/Python/W"
  seq_files: ["K2_EEG1_S-KET.csv"]
  out_seperator: "\t"
